### ISSUE TITLE
User or password not valid for database

### ISSUE THREAD

**Issue by tansydev** [orientechnologies/orientdb-jdbc#26] opened 2015-06-03 12:15 UTC
Hi.
I'm using orientdb-community.2.0.10. and my jdbc driver version is also OrientDB JDBC Driver 2.0.10 ALL.
so, when my application was connected, orientdb was proceeded error.
com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: 'pan_plus_story'
com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: 'pan_plus_story'
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.authenticate(OSecurityShared.java:171)
	at com.orientechnologies.orient.core.metadata.security.OSecurityProxy.authenticate(OSecurityProxy.java:87)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:260)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:647)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:652)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:283)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

my orientdb-server-config.xml.
    <users>
        <user resources="*" password="vmffjtmelql!@@)" name="root"/>
        <user resources="connect,server.listDatabases,server.dblist" password="guest" name="guest"/>
    </users>

but, orientdb-community-2.0.8, 2.0.9 are not error proceed.

**Comment by luigidellaquila** [comment] 2015-06-04 10:18
Hi @tansydev 

two questions:

1. Did you copy your db from 2.0.8-9 to 10?

2. Have you tried to connect from Studio? Maybe the problem is related to the core and not to JDBC driver.

**Comment by tansydev** [comment] 2015-06-05 04:17
Hi.luigidellaquila

1. I'm sorry but i was deleted all db.
    because, i have not enough to time. so, all orientdb is same version.
that is 2.0.8
    but, i will try make same situation, asap.
2. i don't have tried to connect from studio. I will try connect from
studio, later.

asap, i will try make same situation on test bed.
thank you for your reply.

regard,
bryan.


2015-06-04 19:18 GMT+09:00 luigidellaquila <notifications@github.com>:

**Comment by tansydev** [comment] 2015-06-08 10:59
Hi, luigidellaquila.

1. After upgrade from 2.0.8 to 2.0.10, same situation proceeded.
   but, it does no problem studio.
how can i attached my db file?

**Comment by luigidellaquila** [comment] 2015-06-11 06:03
Hi @tansydev 

if it's small enough, you can send it to support - at - orientdb.com
Otherwise you can try with DropBox or another similar service

**Comment by tansydev** [comment] 2015-06-11 06:49
Hi, luigidellaquila.

thank you for your reply.

i send link url via google drive.

https://drive.google.com/file/d/0B1vpqh6fMf4zVzI0TWs2eE5DWWc/view?usp=sharing

check my database file, plz.

regards,
bryan.

2015-06-11 15:03 GMT+09:00 luigidellaquila <notifications@github.com>:

**Comment by lvca** [comment] 2015-06-11 10:57
What happens if you put the database under a server an you login into it by using the server's root credentials?

**Comment by tansydev** [comment] 2015-06-11 11:14
already, orientdb is running by root

2015-06-11 19:57 GMT+09:00 Luca Garulli <notifications@github.com>:

**Comment by pm-raghunandan-gupta** [comment] 2015-06-11 11:49
Hi Luka, I just want to know does Orient DB support transactions like neo4j??
thank you.

**Comment by lvca** [comment] 2015-06-11 12:33
@pm-raghunandan-gupta Sorry this is not the right issue to ask it. Please use the Community Group: https://groups.google.com/forum/#!forum/orient-database

**Comment by tansydev** [comment] 2015-06-22 06:11
hi.luigidellaquila.
I resolved this problem.
i think this problem is orientdb-2.0.9 belower version and my solution.
1. my solution defined propery for db-connect.
   url=remote:host:port/
   user=root
   password=password
  when i called property, i used get passwd. 
  so, password property is null value. 
  In this situation, orientdb-2.0.8 was no problem. but, orientdb 2.0.10 later was problem. 
 Problem message is "User or password not valid for database: 'pan_plus_story'"

so, i think this problem is both orientdb-2.0.8 and my solution.
now, i had upgrade orientdb-2.0.11 and there is no problem.

please, close this issue.

and sorry for my english.

thank you for your helping.

regards,
bryan.

**Comment by luigidellaquila** [comment] 2015-06-22 12:53
hi @tansydev 

Thank you very much for the feedback. Closing

**Closed by luigidellaquila** 2015-06-22 12:52 UTC
